artifact_uri: file:///D:/Projects/Visionary tracker/visionary tracker/runs/mlflow/426009095398328405/5bbc53f5cc12498ebe348f7e04be49bb/artifacts
end_time: null
entry_point_name: ''
experiment_id: '426009095398328405'
lifecycle_stage: active
run_id: 5bbc53f5cc12498ebe348f7e04be49bb
run_name: visionary_tracker_train
run_uuid: 5bbc53f5cc12498ebe348f7e04be49bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1743603661647
status: 1
tags: []
user_id: zinju
