artifact_location: file:///D:/Projects/Visionary tracker/visionary tracker/runs/mlflow/514913595336923849
creation_time: 1743602542989
experiment_id: '514913595336923849'
last_update_time: 1743602542989
lifecycle_stage: active
name: /Shared/Ultralytics
