artifact_location: file:///D:/Projects/Visionary tracker/visionary tracker/runs/mlflow/0
creation_time: 1743602542967
experiment_id: '0'
last_update_time: 1743602542967
lifecycle_stage: active
name: Default
